name: Deploy to CyberFolks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp # jeśli nie działa, zmień na "ftp" albo "sftp"
          port: ${{ secrets.FTP_PORT }} # możesz dodać secret FTP_PORT = 21 albo 22
          server-dir: /public_html/ # <- tu zazwyczaj trafia strona na CyberFolks
          passive: true
