name: Deploy to CyberFolks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp # plain FTP, change to "ftps" if server requires TLS
          port: ${{ secrets.FTP_PORT }} # usually 21 for FTP, 990 for FTPS
          server-dir: /public_html/
          dangerous-clean-slate: true # optional: clears remote files before upload
          timeout: 60 # increase timeout to avoid FIN packet errors
          log-level: info # optional: see detailed logs
